version: 2.0
jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Test the commit
          command: gradle test
      - store_test_results:
          path: test/test-results
  package:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Create the package
          command: gradle jar
      - store_artifacts:
          path: package/libs
          destination: prefix
workflows:
  version: 2
  myworkflow:
    jobs:
      - test
      - package:
        requires:
          - test